services:
  - type: web
    name: threed-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: threed_db
          property: host
      - key: DB_USER
        fromDatabase:
          name: threed_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: threed_db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: threed_db
          property: database
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: threed_db
    databaseName: threed_db
    ipAllowList: [] 